# Generated by Django 4.1 on 2022-08-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_alter_phone_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='slug',
        ),
        migrations.AddField(
            model_name='phone',
            name='URL',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
