# Generated by Django 4.1 on 2022-08-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_remove_phone_slug_phone_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='URL',
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
