# Generated by Django 4.1 on 2022-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(db_index=False, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
